name: auto_smooth_corners
description: A Flutter package for creating smooth, customizable corners in your UI with support for various corner styles and animations.
version: 1.0.0+1
repository: https://github.com/zahir-patel/auto_smooth_corners
homepage: https://github.com/zahir-patel/auto_smooth_corners#readme
documentation: https://github.com/zahir-patel/auto_smooth_corners#readme

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# Publish to pub.dev
publish_to: 'https://pub.dev'

topics:
  - flutter
  - ui
  - corners
  - widgets
  - smooth-ui
  - flutter-widgets

# The following section is specific to Flutter.
# For more information on using Flutter, see https://flutter.dev/

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.5.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  test: ^1.24.0
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
# For more information on using Flutter, see https://flutter.dev/

# The following line ensures that the Material Icons font is
# included with your application, so that you can use the icons in
# the material Icons class.
uses-material-design: true

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages

# Exclude PRD from pub publishing
exclude:
  - PRD/
  - .gitignore
  - .metadata
  - .packages
  - .vscode/
  - .idea/
  - .dart_tool/
  - build/
